# Taken from https://github.com/napi-rs/napi-rs/blob/main/.github/workflows/docker.yaml
# and modified to build with latest rust and node 22
name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker/**"

permissions:
  contents: read
  packages: write

jobs:
  build-alpine:
    name: Build Alpine image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Alpine image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/nodejs-rust:alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-debian:
    name: Build Debian image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Debian image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/debian.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/nodejs-rust:debian
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-debian-aarch64:
    name: Build Debian ARM64 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install latest libc++-dev for cross build
        uses: addnab/docker-run-action@v3
        with:
          image: node:lts-slim
          options: "--platform linux/arm64 --user 0:0 -v ${{ github.workspace }}/lib/llvm-18:/usr/lib/llvm-18"
          run: >-
            apt-get update &&
            apt-get install -y wget gnupg2 &&
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&
            echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main" >> /etc/apt/sources.list &&
            echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main" >> /etc/apt/sources.list &&
            apt-get update &&
            apt-get install libc++-18-dev libc++abi-18-dev -y --fix-missing --no-install-recommends &&
            rm /usr/lib/llvm-18/lib/libc++abi.so

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Debian ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/debian-aarch64.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/nodejs-rust:debian-aarch64
          cache-from: type=gha
          cache-to: type=gha,mode=max
